### ISSUE TITLE
Actual command names instead of command numbers

### ISSUE THREAD

**Issue by mridulmeh** [jaclu010/touch-bar-commands#1]
Can we have actual command names instead of command numbers. It is easier to work that way.

**Comment by jaclu010** [comment]
Hi! Thank you for your interest, though I am unsure of what you mean? On the touchbar or in the command palette?

Other suggestions?

**Comment by mridulmeh** [comment]
On the touchbar. I saw your known issues that due to VSCode Limitations, we cannot have dynamic text. How about we have an extension that can dynamically generate the text and feed it into this extension. We can then potentially bundle them together and run them. I am not sure how it will work out, I am still new to the VS Code extension scene.

**Comment by jaclu010** [comment]
I like that you wan't to fix this, and I think your idea is a bit obscure 😄 

On the other hand it can be solved locally:

1. Find the location where VSCode extensions are installed
 (mine is ` ~/.vscode/extensions/jjlundberg.touch-bar-commands-1.0.0`)
2. Open `package.json`
3. Change the `"title": ` tags to whatever you like
4. Reload the windows or restart VSCode and the icons will have your provided names

However, keep in mind that these setting may be overwritten when new versions are released

Hope this helps!

**Comment by mridulmeh** [comment]
Oh yes, i already am using a locally published version for my use case. I had a go through the API for VS Code and saw we cannot make them dynamic in this repo. 
Anyway, thank you for the help. I will contact you further if I find a solution for this.
