### ISSUE TITLE
How do you code the custom commands

### ISSUE THREAD

**Issue by lanceolenik** [jaclu010/touch-bar-commands#2]
For the `Touch-bar-commands > Command: 1` box, I've put the following:

`{"key":"cmd+C", "command":"touch-bar-commands.execute.cmd1"}`

When I run that, the terminal outputs: `bash: {key:cmd+C,: command not found`

Not sure what should be entered. I'm trying to set up a button that does copy and one that does paste.

**Comment by jaclu010** [comment]
Hi @lanceolenik ,
Thank you for downloading and using the plugin!

First of all, the line 
`{"key":"cmd+C", "command":"touch-bar-commands.execute.cmd1"}` is supposed to be written in the `keybindings.json` file in the VSCode config to add a shortcut from the key `CMD+C` to the `"touch-bar-commands.execute.cmd1"` command.


I am not sure what you are trying to achieve, is it one of

1. That you keybind one of the commands to `CMD+C`
2. When the touch bar button is pressed, a copy `CMD+C` action is taking place

In the case of `1`, the keybindings are found either by navigating to `Code > Preferences > Keyboard Shortcuts`, and there you can search for `Touch Bar Commands` and add your short cut keys there. More reading on [this link](https://code.visualstudio.com/docs/getstarted/keybindings).

In the case of `2`, notice that the command is run in a terminal window. All that is possible in your standard terminal will be possible here. So in the case of copying, it would be to issue the same linux command your OS do when you press `CMD+C`.

I'm sorry for not making the README clear enough, will look into how to improve it. Hope this helps!

**Comment by jaclu010** [comment]
Have this helped? I will close the issue until further notice!
